"""HUMAN_AI_REPOSITORY_DOCUMENTATION_GUIDE의 실행 가능한 문서 계약."""

# ruff: noqa: E501

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DocumentContract:
    name: str
    purpose: str
    owns: str
    references: str
    excludes: str
    sections: tuple[str, ...]


DOCUMENT_CONTRACTS: dict[str, DocumentContract] = {
    "REQUIREMENTS.md": DocumentContract(
        "REQUIREMENTS",
        "무엇을 왜 만들어야 하는지 결정하는 제품 요구사항 SSOT",
        "문제·목표·범위·BIZ/FR/NFR/DATA/AC와 전체 추적성",
        "조사 증거와 ASR/ADR/TASK/TEST/RC/REL 링크",
        "기술 구현 방식·작업 진행률·테스트 절차·배포 명령",
        (
            "문서 정보",
            "배경과 문제",
            "제품 목표",
            "대상 사용자와 이해관계자",
            "운용 개념",
            "사용자 리서치와 근거",
            "가정·제약·의존성",
            "포함 범위",
            "비범위",
            "사용자 흐름과 상태",
            "기능 요구사항",
            "비기능 요구사항",
            "데이터·보안 요구사항",
            "수용 기준",
            "성공 지표",
            "요구사항 추적표",
            "미해결 질문",
            "변경 이력",
        ),
    ),
    "ARCHITECTURE.md": DocumentContract(
        "ARCHITECTURE",
        "요구사항을 구현할 구조·데이터·인터페이스를 결정하는 기술 계약",
        "시스템 경계·컴포넌트·데이터 모델·내부 계약·ASR/ADR",
        "요구사항·SEC·OpenAPI",
        "제품 범위·작업 상태·테스트 결과·출시 승인",
        (
            "문서 정보",
            "설계 목표",
            "관련 요구사항과 ASR",
            "현재 구조",
            "변경 후 구조",
            "C4 모델",
            "컴포넌트 책임",
            "데이터 흐름",
            "API·이벤트 계약",
            "데이터 모델",
            "인증·권한·보안",
            "오류 처리",
            "마이그레이션",
            "호환성",
            "성능·확장성",
            "기술적 위험",
            "주요 결정과 ADR",
            "설계 품질 게이트",
        ),
    ),
    "AGENTS.md": DocumentContract(
        "AGENTS",
        "AI Agent가 저장소에서 지킬 행동·검증·보고 규칙",
        "적용 경로·명령·코딩·안전·승인·보고 규칙",
        "모든 상세 SSOT 문서",
        "기능 범위·기술 계약·테스트 기대 결과·배포 승인",
        (
            "적용 범위",
            "문서 우선순위",
            "프로젝트 구조",
            "설치·실행 방법",
            "테스트·린트·빌드 명령",
            "코딩 규칙",
            "재사용할 구성요소",
            "수정 금지 영역",
            "데이터·보안 규칙",
            "승인 필요 작업",
            "코드 리뷰 규칙",
            "품질 게이트",
            "완료 보고 형식",
            "하위 지침·오버라이드",
            "상세 문서 링크",
        ),
    ),
    "IMPLEMENTATION_PLAN.md": DocumentContract(
        "IMPLEMENTATION_PLAN",
        "요구사항을 실행 가능한 작업으로 바꾸고 현재 상태를 관리하는 살아 있는 문서",
        "TASK·순서·담당·상태·차단·CHG 영향·인수인계",
        "요구사항·ADR·TEST 실행 결과",
        "요구사항 원문·설계 계약·테스트 절차·출시 승인",
        (
            "문서 정보",
            "구현 목표",
            "작업 목록",
            "우선순위",
            "선행 조건과 의존성",
            "담당자·담당 Agent",
            "협업·변경 절차",
            "단계별 구현 계획",
            "변경 파일",
            "검증 증거",
            "차단 요소와 미해결 질문",
            "변경·영향 이력",
            "현재 상태",
            "인수인계",
        ),
    ),
    "TEST_PLAN.md": DocumentContract(
        "TEST_PLAN",
        "요구사항 완료 여부를 검증하고 실제 증거를 보존하는 SSOT",
        "TEST·환경·절차·기대 결과·PASS 기준·실제 결과·증거",
        "REQ/AC·설계 위험·TASK/REL",
        "제품 범위·구현 순서·최종 배포 승인",
        (
            "문서 정보",
            "테스트 목적과 범위",
            "제외 범위",
            "테스트 환경",
            "테스트 지역 추적표",
            "정상 시나리오",
            "오류·예외 시나리오",
            "경계값",
            "권한별 테스트",
            "데이터·마이그레이션 테스트",
            "접근성 테스트",
            "보안 테스트",
            "회귀 테스트",
            "자동 검증 명령",
            "수동 확인 항목",
            "테스트 품질 게이트",
            "테스트 결과",
            "알려진 제한",
        ),
    ),
    "RELEASE_RUNBOOK.md": DocumentContract(
        "RELEASE_RUNBOOK",
        "검증된 변경을 안전하고 재현 가능하게 출시·운영하는 절차",
        "RC/REL·승인·배포·관찰·중단·롤백·실제 결과",
        "요구사항 범위·TEST 결과·마이그레이션",
        "제품 요구·설계·테스트 PASS 기준",
        (
            "문서 정보",
            "릴리스 범위",
            "Definition of Done",
            "버전과 대상 커밋",
            "배포 artifact",
            "배포 전 조건",
            "환경별 설정",
            "빌드·배포 명령",
            "마이그레이션 순서",
            "기능 플래그",
            "승인·권한자",
            "제한 공개·카나리",
            "모니터링 지표",
            "성공·실패 판단",
            "중단·롤백 조건",
            "롤백 절차",
            "장애 대응·에스컬레이션",
            "백업·복구",
            "릴리스 결과",
        ),
    ),
    "SECURITY_PRIVACY.md": DocumentContract(
        "SECURITY_PRIVACY",
        "자산·신뢰 경계·보안·개인정보 요구와 검증 기준의 위험 기반 SSOT",
        "분리 후 SEC·위협·통제·개인정보 생명주기·잔여 위험",
        "제품 요구·설계·TEST-SEC 실행 결과",
        "일반 기능 범위·전체 구조·보안 테스트 실제 결과",
        (
            "보안 범위",
            "보호 대상 자산",
            "신뢰 경계",
            "위협 모델",
            "보안 요구사항",
            "인증",
            "인가",
            "입력값 검증",
            "암호화",
            "개인정보 생명주기",
            "로그·비밀정보",
            "외부 서비스·공급망",
            "OWASP ASVS 매핑",
            "보안 테스트",
            "사고 대응",
            "잔여 위험·승인",
        ),
    ),
    "MIGRATION_PLAN.md": DocumentContract(
        "MIGRATION_PLAN",
        "기존 데이터를 안전하게 변경하고 실패 시 복구하기 위한 실행 절차 SSOT",
        "변환·백업·재실행·검증·중단·복구 절차",
        "데이터 모델·DATA/TASK/TEST/RC/REL",
        "제품 데이터 모델 원문·전체 배포·최종 승인",
        (
            "변경 목적",
            "대상 데이터",
            "기존·신규 스키마",
            "데이터 변환 규칙",
            "사전 백업",
            "마이그레이션 명령",
            "멱등성과 재실행",
            "단계별 검증",
            "중단 조건",
            "롤백",
            "성능·소요 시간",
            "승인자·실행자",
            "실행 결과",
            "복구 확인",
        ),
    ),
    "DELIVERY_CHECKLIST.md": DocumentContract(
        "DELIVERY_CHECKLIST",
        "1인 로컬 프로토타입의 구현·검증·전달 책임을 한 문서에서 관리하는 SSOT",
        "CHG/TASK, TEST 실행 결과와 증거, RC/REL 전달 결과",
        "REQUIREMENTS·ARCHITECTURE·AGENTS의 원본 계약",
        "요구사항 원문·기술 설계 원문·기본 6문서와의 병행 사용",
        (
            "문서 정보",
            "implementation",
            "verification",
            "delivery",
            "현재 상태와 인수인계",
            "변경 이력",
        ),
    ),
}


CORE_DOCUMENTS = (
    "REQUIREMENTS.md",
    "ARCHITECTURE.md",
    "AGENTS.md",
    "IMPLEMENTATION_PLAN.md",
    "TEST_PLAN.md",
    "RELEASE_RUNBOOK.md",
)
